### ISSUE TITLE
Content: The last column of tables (usually actions) should be aligned to the right

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/protonmail-settings#108]
Reported by Keven: ![image](https://user-images.githubusercontent.com/2578321/63087703-1a8ab700-bf53-11e9-98c0-0b34c5f84ab1.png)

Add class `alignright` to last `td`/`th`.

I've sent a fix on Design System in order to make it work on `th` https://design-system-beta.netlify.com/table/ 

If you prefer adding a modifier on tables like `pm-simple-table--last-column-action` that does it via CSS (because there will always be exceptions ^^), please tell me.

**Comment by EpokK** [comment]
@nico3333fr can you please add a CSS class on the table to handle that?

**Comment by nico3333fr** [comment]
@EpokK no problem, will add it asap :)

**Comment by nico3333fr** [comment]
Well, I had a few minutes in the train, so it is added: https://github.com/ProtonMail/design-system/commit/7e9830669a7e9d23229484d6b13d23c61cbea478 (use `pm-simple-table--has-actions` modifier on table to achieve it)
