### ISSUE TITLE
PayPal can't be added as a payment method

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/protonmail-settings#111]
When you try to add PayPal as a payment method, the process gets stuck on https://secure.protonmail.blue/ and never completes:

**Example:**

![KG6ew2PSyQ](https://user-images.githubusercontent.com/44697797/63425621-47d2db80-c411-11e9-8ecb-411ffe411a78.gif)

**Comment by EpokK** [comment]
It's because the app is checking for `https://secure.protonmail.com`, not `https://secure.protonmail.blue`.
