### ISSUE TITLE
Typo in  protonmail-settings/po/template.pot 

### ISSUE THREAD

**Issue by sveinki** [ProtonMail/protonmail-settings#28]
#: node_modules/react-components/containers/addresses/AddressActions.js:81
msgctxt "Address action"
msgid "Generate missing keus"
msgstr ""

'keus' --> 'keys'

**Comment by dhoko** [comment]
:wave: 

thx, fixed via https://github.com/ProtonMail/react-components/commit/b9287b7d11206a74d5bf9ca6f1df69085b9255b4
