### ISSUE TITLE
Order addresses

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/protonmail-settings#36]
Let the current user re-order his addresses.

Component: `<AddressesWithUser />`

**Comment by mmso** [comment]
![Screenshot 2019-07-31 at 10 10 38](https://user-images.githubusercontent.com/352607/62195069-79f59e00-b37b-11e9-9688-0c34a44c3d24.png)

I think it also needs to be added in `<AddressesWithMembers />` for the case when `member.Self` is selected?
