### ISSUE TITLE
Authentication logs are downloaded one page at a time

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonmail-settings#40]
**Steps to reproduce**
1. Go to Security
2. Scroll down to authentication logs
3. Click download 

**Expected behavior**
The complete list of authentication logs should be downloaded. 

**Current behavior**
Only the data from the current page is downloaded.

**Comment by dhoko** [comment]
fix via https://github.com/ProtonMail/react-components/pull/98
