### ISSUE TITLE
Invoices always have a page 2 available

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/protonmail-settings#44]
Both user and organization invoices always allow to open page 2 for invoices, despite no invoices being available on page 2:

![invoice page 2](https://user-images.githubusercontent.com/44697797/58616863-01ad2680-82bf-11e9-84fe-5863c40a7876.png)

**Comment by dhoko** [comment]
Fix https://github.com/ProtonMail/react-components/pull/97
