### ISSUE TITLE
Invoice preview doesn't work on first try

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/protonmail-settings#45]
**Description:**
When you try to preview an invoice, the preview never works on the first open.

You have to close the preview and re-open the invoice for a second time in order to see the preview.

**Video:**
[invocie preview.mov.zip](https://github.com/ProtonMail/protonmail-settings/files/3235960/invocie.preview.mov.zip)

Additionally, the `submit` button doesn't work and outputs an error in the console.

ROOT_DIR=/Users/Em/Documents/GitHub
Tested on Chrome 74, macOS 10.14

**Comment by dhoko** [comment]
Fix https://github.com/ProtonMail/react-components/pull/97
