### ISSUE TITLE
Password reset & daily email notifications will stay enabled without recovery email

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonmail-settings#46]
**Steps to reproduce**
1. Set recovery email
2. Enable recovery
3. Enable daily email notifications
4. Delete the recovery email.

**Expected behavior**
Email recovery without recovery address is impossible. The same applies to daily email notifications. I expected these options to be turned off. The user should see a warning before these options are turned off.

**Current behavior**
I can have daily email notifications & password recovery without recovery email.

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/1968a366b7a2075e7c2df331e4a057fef380f36a
