### ISSUE TITLE
Missing anchor for delete account section

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonmail-settings#47]
**Steps to reproduce**
1. Go to account
2. Click delete account on the right menu.

**Expected behavior**
The app should jump to delete account section.

**Current behavior**
Nothing happens.

**Comment by emnproton** [comment]
Note: the whole `delete account` section seems to be incomplete.

The label for the section says `irreversible action` which is not how it's designed on Zeplin:

![irreversible action](https://user-images.githubusercontent.com/44697797/58688348-78602780-8384-11e9-99ad-0c1f6972a3be.png)

Additionally, the `irreversible action` label and row is fully clickable and brings up the delete account modal without actually having to click on the delete button.

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/91a6f9e88969d6abd13021ce623b8d5194fe4399
