### ISSUE TITLE
Update Buttons in Subscription Settings

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/protonmail-settings#54]
In the Plans section of the page
- can you please update the SELECT button of the *active plan* to say UPDATE

In the Subscription section of the page
- can you please update the MANAGE button next to the selected paid ProtonMail plan name to say UPDATE as well
- can you please update the MANAGE button next to the selected paid ProtonVPN plan name to say UPDATE as well

Also, please verify the following conditions:
- If the user is susbcribed to the FREE Mail Plan and presses on the UPDATE button, the user is notified that there is nothing that can be updated on FREE plan

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/3177320aa7a13ba39e850ab6222c5cc393bf9fa6
