### ISSUE TITLE
Modal window in 'Identity' is not shown accordingly

### ISSUE THREAD

**Issue by DaraQA** [ProtonMail/protonmail-settings#56]
The modal window is not shown accordingly:

1. Open 'Settings'
2. Click on 'Identity' on the navigation bar
3. Click on 'Edit' next to 'Display name'
4. Click on 'Edit' next to 'Signature'

![Screenshot_7](https://user-images.githubusercontent.com/50198984/61046468-83739200-a3dd-11e9-928d-d4d4aa2849f0.png)

**Comment by DaraQA** [comment]
The same issues is in 'Addresses' also

1. Open 'Settings'
2. Click on 'Addresses' on the navigation bar
3. Click 'Edit' in the 'Actions' column

![image](https://user-images.githubusercontent.com/50198984/61060853-82515d80-a3fb-11e9-9b13-82fc423a2d92.png)

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/20f138d167d8579705ac1342482d2ab581df2142
