### ISSUE TITLE
Folder notification toggles goes back and forth before changing status

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/protonmail-settings#58]
When enabled, clicking on the folder notification toggle will make the toggle get to the middle of the switch, then return it back to enabled, before finally goes to the disabled position.

**Video:**
[UDubiGnirN.zip](https://github.com/ProtonMail/protonmail-settings/files/3382030/UDubiGnirN.zip)

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/d4a8932abb49d1c1da14fc144800f0cc2db1e2bc
