### ISSUE TITLE
Zooming in cuts the text in the 'Pricing' fields

### ISSUE THREAD

**Issue by DaraQA** [ProtonMail/protonmail-settings#59]
**Description**

When I zoom in the values in the 'Pricing' boxes are shown with partially, the text is cut. 

**To Reproduce**

1. Open the 'Settings'
2. Click on 'Subscription' in the nav bar
3. Click in 'Show plans'
4. Zoom in 
5. Observe the 'Pricing' boxes'

**Expected behavior**

The selected values are shown without being cut.

**Video**

https://recordit.co/da0FDvyvoG

**Comment by nico3333fr** [comment]
@DaraQA I don't know if this have been updated, but zooming seems ok for me:

https://recordit.co/UukpsYEDWQ
