### ISSUE TITLE
Trying to enable daily email notifications, results with an error

### ISSUE THREAD

**Issue by DaraQA** [ProtonMail/protonmail-settings#61]
**Description**

When I try to enable daily email notifications, I receive 'Invalid input' error.

**Steps to reproduce the behavior:**

1. Open 'Settings'
2. Click on 'Account'
3. In the 'Recovery & notification' section click on the 'Daily email notifications' toggle
4. Enter the account's password
5. Click 'Submit'	

**Expected behavior**

The 'Daily email notifications' are enabled.

**Video**

https://recordit.co/ntrcMpFXFM

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/20f138d167d8579705ac1342482d2ab581df2142
