### ISSUE TITLE
Missing notification when changing email subscriptions

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/protonmail-settings#62]
If you try to disable/enable the email subscriptions in `/account`, there is no notification shown whether the action was successful or not.

**Video:**

[bpVqnBd2CD.zip](https://github.com/ProtonMail/protonmail-settings/files/3385525/bpVqnBd2CD.zip)

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/d0a615621a24750fc3b5c03adb3546f7f63add7b
