### ISSUE TITLE
'Revoke all other sessions' does not revoke the active sessions

### ISSUE THREAD

**Issue by DaraQA** [ProtonMail/protonmail-settings#63]
In 'Security' is not possible to revoke all active sessions at the same time by clicking 'Revoke all other sessons'

**Video:**

https://recordit.co/wT7GIt8ava

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/20f138d167d8579705ac1342482d2ab581df2142
