### ISSUE TITLE
Missing notifications for external PGP settings

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/protonmail-settings#64]
The `external PGP settings` panel in `/settings/security` does not fire any kind of notifications when you toggle the switches or change the default PGP scheme in the dropdown.

**Video:**
[Lj6voKIw7F.zip](https://github.com/ProtonMail/protonmail-settings/files/3385606/Lj6voKIw7F.zip)

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/980ed633858e9c49f95606b48807f7410221e4bb
