### ISSUE TITLE
Clicking Settings button breaks the html/css

### ISSUE THREAD

**Issue by nikolanol** [ProtonMail/protonmail-settings#65]
Clicking Settings button while already in Settings breaks the html/css

![](http://g.recordit.co/vEm1WB6pyn.gif)

**Comment by vincaslt** [comment]
1. https://github.com/ProtonMail/protonmail-settings/pull/81
2. https://github.com/ProtonMail/react-components/pull/133
3. https://github.com/ProtonMail/design-system/pull/171
