### ISSUE TITLE
Change credit card payment option name

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/protonmail-settings#68]
This is a suggestion from several users who use debit cards in order to pay for their ProtonMail/ProtonVPN subscriptions.

**The current wording of the Payment Method is 'Credit Card' only, and that can be misleading to some users who want to pay with a Debit Cards.** Since we already accept Debit Card Payments too, it would be more useful to mention that we accept debit cards as well in the Payment Sections. 

**The wording could be changed to 'Credit/Debit Card', 'Credit / Debit Card', 'Credit or Debit Card' or 'Payment Card (Credit/Debit)'.**

I believe this would add better clarification and it would improve the user experience.

---

**Screenshot:**

![Screenshot_8](https://user-images.githubusercontent.com/44697797/61300876-1861fb00-a7e3-11e9-94fe-1162ed51ffb1.png)

**Actual result:**

Dropdown option is "pay with credit card"

**Expected result:**

Dropdown should say "pay with credit/debit card" or similar alternative (@jovanjovanovski can add a suggestion).

**Comment by EpokK** [comment]
Done: https://github.com/ProtonMail/react-components/commit/64deb04ea45390b8efac5d7d9a9aa348e05f987d

**Comment by emnproton** [comment]
Noticed the `add credit card` button in payment methods doesn't have the same text as in the dropdown (which is `pay with credit / debit card`).

![2019-08-25_154901](https://user-images.githubusercontent.com/44697797/63650891-edf34e00-c74f-11e9-9d0d-f2d1e5c1ca15.jpg)

To use the same convention, the button in the screenshot should say `Add credit / debit card`.
