### ISSUE TITLE
Add general dropdown

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/protonmail-settings#69]
![Capture d’écran 2019-07-16 à 17 40 25](https://user-images.githubusercontent.com/1345786/61308582-d8097980-a7f0-11e9-8d88-c6aa55569eab.png)

### Note
- Check current behavior on `mail.protonmail.com`
- Remove "Tutorials & Help" because there is no tutorial on other web-apps
- Contact support open new tab to https://protonmail.com/support-form
- Report bug opens the bug report modal
- Proton Shop goes to https://shop.protonmail.com
- Support us open the `<DonateModal />`
- This will be used by ProtonCalendar, ProtonContacts and ProtonMail Settings.
- Remove version number since it's different between 4 web-apps.

**Comment by matstaz** [comment]
After speaking to Richard, I agree with all the comments. With one exception. We should replace tutorial and help with a link to the knowledge base on static. So it would look like this:

Troubleshooting & help > https://protonmail.com/support/
Contact support > https://protonmail.com/support-form
Report bug > open report bug modal
Proton shop > https://shop.protonmail.com
Support us > open donate modal

**Comment by matstaz** [comment]
Yes. You can remove the app version. But consider also the case where we reload tab.

![Reload Tab](https://user-images.githubusercontent.com/40168570/61355099-ea78c700-a873-11e9-8c56-d5c5ec147448.png)

Also, note that when the drop down is closed and the "reload tab" request has been triggered, the user must see the badge that attracts user's attention

<img width="468" alt="Capture d’écran 2019-07-17 à 09 20 07" src="https://user-images.githubusercontent.com/40168570/61355238-375c9d80-a874-11e9-9956-99c24db7ced3.png">

**Comment by EpokK** [comment]
@matstaz how do you want to attract user's attention when a new version is available? Do you have a design or UI proposal?

**Comment by matstaz** [comment]
@EpokK yes. Here is is:

![image](https://user-images.githubusercontent.com/40168570/61356152-05e4d180-a876-11e9-8d97-0a236b1c59b9.png)

**Comment by EpokK** [comment]
@Yiin add a link to `/settings` at the top of the list (above tutorial).
