### ISSUE TITLE
Sticky labels setting is hidden when conversation mode is disabled

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonmail-settings#70]
**Steps to reproduce**
1. Go to settings
2. Go to appearance
3. Enable conversation mode
4. Enable sticky labels
5. Enable single message mode.
6.  Enable conversation mode

**Expected behavior**
The sticky labels are independent of the conversation mode. I would expect one of these situations:

1. Sticky labels to be separate setting, independent of the conversation mode setting.. 
or
2. Sticky labels to be turned off when conversation mode is turned off.

**Comment by matstaz** [comment]
@RandomAdversary Not sure I understand.

Stickly label can ONLY be enabled if conversation mode is enabled. the behavior is correct in my opinion.

**Comment by RandomAdversary** [comment]
@matstaz In the current api implementation the sticky labels will stay enabled, even when the conversation mode is disabled. 

This issue is to make sure the frontend code matches the backend implementation. If you believe this is the wrong behavior, please coordinate with the backend team and let us know when the final decision has been made.

**Comment by EpokK** [comment]
OK then we can turn this parameter to off on our side also.

**Comment by matstaz** [comment]
I see. OK. So when you disable conversation mode, you want also to disable Sticky label so that when I re-enable conversation mode, the defautl value for sticky label will be OFF and I can turn it back ON
