### ISSUE TITLE
Wrong navigation from 'Users' to 'Addresses', when you want to manage user's addresses

### ISSUE THREAD

**Issue by DaraQA** [ProtonMail/protonmail-settings#72]
The navigation from 'Users' to 'Addresses' is not correct.
It doesn't matter which user's addresses you want to manage, the primary admin user is opened every time.

User: trpence@protonmail.com
pass: 12345

1. Account with enabled 'Multi-user'
2. Open 'Settings'
3. Open 'Users'
4. Click on the drop down list in the 'ADDRESSES' column
5. Click 'Manage'

**Expected result:**

You should be navigated in 'Addresses', and the addresses of the correct user should be listed.

**Video:**
https://recordit.co/KdVskhu5WF

**Comment by EpokK** [comment]
Here the idea is to pass the `memberID` as parameter when we open the addresses page to preselect the appropriate member.
