### ISSUE TITLE
The previously set time changes, when I edit auto reply's start/end date

### ISSUE THREAD

**Issue by DaraQA** [ProtonMail/protonmail-settings#74]
The previously set time changes, when I edit auto reply's start/end date.
For example, if I change the 'start date', only the 'start time' changes for minus 2 hours of the previously set time, the 'end time' stays the same. 

https://recordit.co/FeixwFhGBH

**Comment by vincaslt** [comment]
Should be fixed by: https://github.com/ProtonMail/protonmail-settings/issues/74
