### ISSUE TITLE
Header doesn't update on display name changes

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonmail-settings#98]
**Steps to reproduce**
1. Go to /settings/identity#name-signature
2. Change the display name
3. Notice the header.

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/62859817-9a6c1380-bcfe-11e9-9837-2aa00fc97ffb.png)

**Comment by RandomAdversary** [comment]
Update: After discussion with @emnproton  we discovered that, this bug is happening when starting the project locally on my machine. When tested on the test(blue) server, it was working as expected.

**Comment by EpokK** [comment]
API not yet deployed.
