### ISSUE TITLE
Email address can be both default and disabled

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonmail-settings#99]
**Summary**
One of the email addresses can be both default and disabled. This leads to inconsistency across the interface because some components are not aware that this is possible.
Example: going to /settings/identity will show the wrong display name for all addresses.

**Steps to reproduce**
1. Login to account with multiple addresses. 
2. Set one address to be default.
3. Disable the address from step 2.

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/62860581-de601800-bd00-11e9-9f42-37de91f9e8db.png)

**Comment by EpokK** [comment]
- [ ] Remove `Disable` action for the primary address.
- [ ] Throw an error if the user try to "unshift" a disabled address.
